# Generated by Django 4.2 on 2023-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('fechaPublicacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=40)),
                ('emailCliente', models.EmailField(max_length=254)),
                ('mensajeCliente', models.CharField(max_length=300)),
                ('nuevo', models.BooleanField()),
                ('telCliente', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=6)),
                ('descrip', models.TextField(default=None)),
                ('fechaRealizaicón', models.DateField(auto_now=True)),
            ],
        ),
    ]
