# Generated by Django 4.2 on 2023-04-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fechaRealizaicón',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
