# Generated by Django 4.2 on 2023-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortafolio', '0002_remove_articulos_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='fechaPubliacaion',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fechaRelaizacion',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
