# Generated by Django 4.2 on 2023-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortafolio', '0003_articulos_fechapubliacaion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='fechaRelaizacion',
            field=models.CharField(max_length=8),
        ),
    ]
