# Generated by Django 4.2 on 2023-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortafolio', '0004_alter_proyectos_fecharelaizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='fechaRelaizacion',
            new_name='fechaRealizacion',
        ),
    ]
